import { transit_realtime } from 'gtfs-realtime-bindings'

// ─── Static GTFS ─────────────────────────────────────────────────────────────
// Loads lookup files generated by `npm run update-gtfs`.
// All fetches are cached in memory for the lifetime of the page.

let stopsCache = null
let directionsCache = null
let shapesCache = null
let stopRoutesCache = null

async function loadJSON(path) {
  const res = await fetch(path)
  if (!res.ok) throw new Error(`Could not load ${path} (${res.status}) — run npm run update-gtfs first`)
  return res.json()
}

export async function getStops() {
  if (!stopsCache) stopsCache = await loadJSON('/gtfs-stops.json')
  return stopsCache
}

export async function getDirections() {
  if (!directionsCache) directionsCache = await loadJSON('/gtfs-directions.json')
  return directionsCache
}

export async function getStopRoutes() {
  if (!stopRoutesCache) stopRoutesCache = await loadJSON('/gtfs-stop-routes.json')
  return stopRoutesCache
}

export async function getShapes() {
  if (!shapesCache) shapesCache = await loadJSON('/gtfs-shapes.json')
  return shapesCache
}

// stopId → "Stop Name"
export function resolveStopName(stops, stopId) {
  if (!stopId || !stops) return null
  const entry = stops[stopId]
  if (!entry) return stopId
  return typeof entry === 'string' ? entry : entry.name
}

// routeId + directionId → headsign string
export function resolveHeadsign(directions, routeId, directionId) {
  if (!routeId) return null
  return directions?.[`${routeId}:${directionId}`]
    ?? directions?.[`${routeId}:0`]
    ?? null
}

// Haversine distance in metres between two lat/lon points
function haversine(lat1, lon1, lat2, lon2) {
  const R = 6371000
  const dLat = (lat2 - lat1) * Math.PI / 180
  const dLon = (lon2 - lon1) * Math.PI / 180
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * Math.sin(dLon / 2) ** 2
  return Math.round(R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)))
}

// Returns stops within maxMeters sorted by distance, capped at maxResults
export function findNearbyStops(stops, lat, lon, maxMeters = 800, maxResults = 20) {
  if (!stops) return []
  return Object.entries(stops)
    .filter(([, s]) => typeof s === 'object' && s.lat && s.lon)
    .map(([id, s]) => ({ id, name: s.name, lat: s.lat, lon: s.lon, dist: haversine(lat, lon, s.lat, s.lon) }))
    .filter(s => s.dist <= maxMeters)
    .sort((a, b) => a.dist - b.dist)
    .slice(0, maxResults)
}

// Simple fuzzy search over stop names, returns up to maxResults matches
export function searchStops(stops, query, maxResults = 10) {
  if (!stops || query.length < 2) return []
  const q = query.toLowerCase()
  return Object.entries(stops)
    .filter(([, s]) => {
      const name = typeof s === 'string' ? s : s.name
      return name.toLowerCase().includes(q)
    })
    .slice(0, maxResults)
    .map(([id, s]) => ({
      id,
      name: typeof s === 'string' ? s : s.name,
      lat: typeof s === 'object' ? s.lat : null,
      lon: typeof s === 'object' ? s.lon : null,
    }))
}

// ─── Realtime GTFS ───────────────────────────────────────────────────────────

const BASE = '/api/gtfs-rt/rtd'

async function decodeFeed(filename) {
  const res = await fetch(`${BASE}/${filename}`)
  if (!res.ok) throw new Error(`RTD feed ${filename} returned ${res.status}`)
  const buffer = await res.arrayBuffer()
  return transit_realtime.FeedMessage.decode(new Uint8Array(buffer))
}

// Vehicle positions → array of vehicle objects
export async function fetchVehiclePositions() {
  const feed = await decodeFeed('VehiclePosition.pb')
  return feed.entity
    .filter(e => e.vehicle?.position)
    .map(e => {
      const v = e.vehicle
      return {
        id: e.id,
        routeId: v.trip?.routeId ?? '',
        tripId: v.trip?.tripId ?? '',
        lat: v.position.latitude,
        lon: v.position.longitude,
        heading: v.position.bearing ?? 0,
        speed: Math.round((v.position.speed ?? 0) * 2.237), // m/s → mph
        vehicleLabel: v.vehicle?.label ?? e.id,
        nextStop: v.stopId ?? null,
        directionId: v.trip?.directionId ?? 0,
        delay: 0, // merged from TripUpdates below
      }
    })
}

// Trip updates → map of tripId → { delay (minutes), etaSec (unix seconds) }
export async function fetchTripDelays() {
  const feed = await decodeFeed('TripUpdate.pb')
  const updates = {}
  for (const e of feed.entity) {
    if (!e.tripUpdate) continue
    const tripId = e.tripUpdate.trip?.tripId
    if (!tripId) continue
    const first = e.tripUpdate.stopTimeUpdate?.[0]
    const delaySec = first?.arrival?.delay ?? first?.departure?.delay ?? 0
    const etaRaw = first?.arrival?.time ?? first?.departure?.time ?? null
    updates[tripId] = {
      delay: Math.round(delaySec / 60),
      etaSec: etaRaw !== null ? Number(etaRaw) : null,
    }
  }
  return updates
}

// Upcoming arrivals at a specific stop, sorted by ETA
export async function fetchArrivalsAtStop(stopId) {
  const [feed, directions] = await Promise.all([
    decodeFeed('TripUpdate.pb'),
    getDirections().catch(() => null),
  ])
  const nowSec = Date.now() / 1000
  const arrivals = []

  for (const e of feed.entity) {
    if (!e.tripUpdate) continue
    const tu = e.tripUpdate
    const routeId = tu.trip?.routeId ?? ''
    const directionId = tu.trip?.directionId ?? 0

    for (const stu of (tu.stopTimeUpdate ?? [])) {
      if (String(stu.stopId) !== String(stopId)) continue
      const etaSec = Number(stu.arrival?.time ?? stu.departure?.time ?? 0)
      if (etaSec > 0 && etaSec < nowSec) continue // already passed
      const delaySec = stu.arrival?.delay ?? stu.departure?.delay ?? 0
      arrivals.push({
        tripId: tu.trip?.tripId ?? '',
        routeId,
        directionId,
        headsign: resolveHeadsign(directions, routeId, directionId),
        etaSec: etaSec || null,
        delay: Math.round(delaySec / 60),
      })
    }
  }

  return arrivals
    .sort((a, b) => (a.etaSec ?? Infinity) - (b.etaSec ?? Infinity))
    .slice(0, 12)
}

const EFFECT_LABEL = {
  1: 'No Service',
  2: 'Reduced Service',
  3: 'Significant Delays',
  4: 'Detour',
  5: 'Additional Service',
  6: 'Modified Service',
  7: 'Other Effect',
  9: 'Stop Moved',
}

function effectToSeverity(effect) {
  if (effect === 1 || effect === 3) return 'warning'
  if (effect === 5 || effect === 6) return 'success'
  return 'info'
}

function translatedText(ts) {
  return ts?.translation?.find(t => t.language === 'en')?.text
    ?? ts?.translation?.[0]?.text
    ?? ''
}

// Alerts → array of alert objects
export async function fetchAlerts() {
  const feed = await decodeFeed('Alerts.pb')
  return feed.entity
    .filter(e => e.alert)
    .map(e => {
      const a = e.alert
      const routeIds = (a.informedEntity ?? [])
        .map(ie => ie.routeId)
        .filter(Boolean)
      const startSec = a.activePeriod?.[0]?.start
      return {
        id: e.id,
        severity: effectToSeverity(a.effect),
        title: translatedText(a.headerText) || 'Service Alert',
        description: translatedText(a.descriptionText),
        route: routeIds[0] ?? null,
        allRoutes: routeIds,
        effectLabel: EFFECT_LABEL[a.effect] ?? 'Alert',
        time: new Date(
          startSec ? Number(startSec) * 1000 : Date.now()
        ).toISOString(),
      }
    })
}
