// Loads lookup files generated by `npm run update-gtfs`.
// All fetches are cached in memory for the lifetime of the page.

let stopsCache = null
let directionsCache = null

async function loadJSON(path) {
  const res = await fetch(path)
  if (!res.ok) throw new Error(`Could not load ${path} (${res.status}) — run npm run update-gtfs first`)
  return res.json()
}

export async function getStops() {
  if (!stopsCache) stopsCache = await loadJSON('/gtfs-stops.json')
  return stopsCache
}

export async function getDirections() {
  if (!directionsCache) directionsCache = await loadJSON('/gtfs-directions.json')
  return directionsCache
}

// stopId → "Stop Name"
export function resolveStopName(stops, stopId) {
  if (!stopId || !stops) return null
  const entry = stops[stopId]
  if (!entry) return stopId
  return typeof entry === 'string' ? entry : entry.name
}

// routeId + directionId → headsign string
export function resolveHeadsign(directions, routeId, directionId) {
  if (!routeId) return null
  return directions?.[`${routeId}:${directionId}`]
    ?? directions?.[`${routeId}:0`]
    ?? null
}

// Haversine distance in metres between two lat/lon points
function haversine(lat1, lon1, lat2, lon2) {
  const R = 6371000
  const dLat = (lat2 - lat1) * Math.PI / 180
  const dLon = (lon2 - lon1) * Math.PI / 180
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * Math.sin(dLon / 2) ** 2
  return Math.round(R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)))
}

// Returns stops within maxMeters sorted by distance, capped at maxResults
export function findNearbyStops(stops, lat, lon, maxMeters = 800, maxResults = 20) {
  if (!stops) return []
  return Object.entries(stops)
    .filter(([, s]) => typeof s === 'object' && s.lat && s.lon)
    .map(([id, s]) => ({ id, name: s.name, lat: s.lat, lon: s.lon, dist: haversine(lat, lon, s.lat, s.lon) }))
    .filter(s => s.dist <= maxMeters)
    .sort((a, b) => a.dist - b.dist)
    .slice(0, maxResults)
}

// Simple fuzzy search over stop names, returns up to maxResults matches
export function searchStops(stops, query, maxResults = 10) {
  if (!stops || query.length < 2) return []
  const q = query.toLowerCase()
  return Object.entries(stops)
    .filter(([, s]) => {
      const name = typeof s === 'string' ? s : s.name
      return name.toLowerCase().includes(q)
    })
    .slice(0, maxResults)
    .map(([id, s]) => ({
      id,
      name: typeof s === 'string' ? s : s.name,
      lat: typeof s === 'object' ? s.lat : null,
      lon: typeof s === 'object' ? s.lon : null,
    }))
}
